# Generated by Django 2.2.7 on 2020-11-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201105_1908'),
        ('common', '0002_auto_20201105_1914'),
    ]

    operations = [
    ]
